import type { HabitDefinition, HabitId } from '@/types'

export const HABITS: Record<HabitId, HabitDefinition> = {
  phone: {
    id: 'phone',
    label: 'Phone Addiction',
    tagline: 'Constant checking, endless scrolling',
    icon: 'Smartphone',
    triggerVocabulary: ['bored', 'notification', 'anxious', 'habit', 'waiting', 'lonely'],
    replacementActivities: ['Take a 5-minute walk', 'Do 10 push-ups', 'Call a friend instead of texting', 'Read one page of a book'],
  },
  instagram: {
    id: 'instagram',
    label: 'Instagram',
    tagline: 'Comparison, FOMO, endless feed',
    icon: 'Camera',
    triggerVocabulary: ['bored', 'comparison', 'fomo', 'lonely', 'validation'],
    replacementActivities: ['Journal one win from today', 'Text a real friend', 'Step outside for 5 minutes', 'Stretch for 2 minutes'],
  },
  facebook: {
    id: 'facebook',
    label: 'Facebook',
    tagline: 'Doomscrolling and notifications',
    icon: 'ThumbsUp',
    triggerVocabulary: ['bored', 'habit', 'news', 'lonely'],
    replacementActivities: ['Message someone directly instead', 'Tidy your space for 5 minutes', 'Go for a short walk'],
  },
  tiktok: {
    id: 'tiktok',
    label: 'TikTok',
    tagline: 'Infinite short-form scroll',
    icon: 'Music2',
    triggerVocabulary: ['bored', 'anxious', 'habit', 'procrastination'],
    replacementActivities: ['Set a 10-minute timer for a hobby', 'Do a quick stretch routine', 'Listen to one full song, eyes closed'],
  },
  gaming: {
    id: 'gaming',
    label: 'Gaming',
    tagline: 'Escapism and compulsive sessions',
    icon: 'Gamepad2',
    triggerVocabulary: ['bored', 'stress', 'escape', 'social', 'habit'],
    replacementActivities: ['Go for a walk outside', 'Do a 10-minute workout', 'Call a friend', 'Work on a small creative project'],
  },
  smoking: {
    id: 'smoking',
    label: 'Smoking',
    tagline: 'Nicotine cravings and habit loops',
    icon: 'Cigarette',
    triggerVocabulary: ['stress', 'habit', 'social', 'after-meal', 'anxious'],
    replacementActivities: ['Chew gum or a mint', 'Do 4-7-8 breathing', 'Drink a glass of water slowly', 'Go for a brisk 5-minute walk'],
  },
  alcohol: {
    id: 'alcohol',
    label: 'Alcohol',
    tagline: 'Drinking to cope or socialize',
    icon: 'Wine',
    triggerVocabulary: ['stress', 'social', 'habit', 'sadness', 'celebration'],
    replacementActivities: ['Make a non-alcoholic drink you enjoy', 'Call a supportive friend', 'Do a short guided meditation'],
  },
  pornography: {
    id: 'pornography',
    label: 'Pornography',
    tagline: 'Compulsive use as escape or stress relief',
    icon: 'ShieldOff',
    triggerVocabulary: ['bored', 'stress', 'lonely', 'anxious', 'habit'],
    replacementActivities: ['Leave the room you\'re in', 'Do a cold-water face splash', 'Go for a walk', 'Call or text a friend'],
  },
  sugar: {
    id: 'sugar',
    label: 'Sugar',
    tagline: 'Cravings and emotional eating',
    icon: 'Candy',
    triggerVocabulary: ['stress', 'habit', 'boredom', 'emotional', 'after-meal'],
    replacementActivities: ['Drink a glass of water first', 'Eat a piece of fruit', 'Chew sugar-free gum', 'Go for a short walk'],
  },
  procrastination: {
    id: 'procrastination',
    label: 'Procrastination',
    tagline: 'Avoidance and task paralysis',
    icon: 'Clock',
    triggerVocabulary: ['overwhelm', 'fear', 'perfectionism', 'boredom', 'fatigue'],
    replacementActivities: ['Work for just 2 minutes', 'Break the task into one tiny step', 'Change your environment', 'Write down what scares you about the task'],
  },
  custom: {
    id: 'custom',
    label: 'Custom Habit',
    tagline: 'Define your own habit to track',
    icon: 'Sparkles',
    triggerVocabulary: ['stress', 'boredom', 'habit', 'social', 'emotional'],
    replacementActivities: ['Take a short walk', 'Practice deep breathing', 'Reach out to someone you trust'],
  },
}

export const HABIT_LIST = Object.values(HABITS)
