import {
  Smartphone,
  Camera,
  ThumbsUp,
  Music2,
  Gamepad2,
  Cigarette,
  Wine,
  ShieldOff,
  Candy,
  Clock,
  Sparkles,
  Zap,
  Coffee,
  Heart,
  Repeat,
  CloudRain,
  MoreHorizontal,
  Award,
  Flame,
  BookOpen,
  ShieldCheck,
  type LucideIcon,
} from 'lucide-react'

/** Central name -> component registry so data-driven icon strings (habits, triggers, achievements) can resolve at render time. */
export const ICONS: Record<string, LucideIcon> = {
  Smartphone,
  Camera,
  ThumbsUp,
  Music2,
  Gamepad2,
  Cigarette,
  Wine,
  ShieldOff,
  Candy,
  Clock,
  Sparkles,
  Zap,
  Coffee,
  Heart,
  Repeat,
  CloudRain,
  MoreHorizontal,
  Award,
  Flame,
  BookOpen,
  ShieldCheck,
}
